sensor_kit_base_link:
  hesai_top_base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  ydlidar_front_base_link:  # ParcelPal in Tianjin China 20250117
    x: 0.133
    y: 0.0
    z: -0.75
    roll:  -3.14159
    pitch: 0.0
    yaw:   -1.5708
  ydlidar_rear_base_link:  # Non in ParcelPal in Tianjin China
    x: -1.06
    y:  0.0
    z: -0.57
    roll:  0.0
    pitch: 0.0
    yaw:   0.0
  tamagawa/imu_link:        # Okinawa testbed center
    x: -0.30
    y: 0.0
    z: -0.795
    roll: 0.0
    pitch: 0.0
    yaw: -3.14159265359
